version: "3.5"

services:

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - 4200:4200
    volumes:
      - ./client:/app:delegated
    networks:
      pdp_project:

networks:
  pdp_project:
    external: true
